### PR TITLE
(fix) revalidated quantity input to decimal from integer, paused and close dispensing

### PR DESCRIPTION
**Pull request by FelixKiprotich350**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Revalidated  quantity input to decimal from integer
Enabled paused and close dispensing feature
Cleaned dispensing payload to collect correct details

## Screenshots
Screenshot from 2024-10-31 17-40-34
Screenshot from 2024-11-06 17-24-16

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ojwanganto** [comment]
Thanks so much @FelixKiprotich350. Kindly group the orders by patient similar to the design for dispensing drugs. Asante

**Comment by FelixKiprotich350** [comment]
> Asante

@ojwanganto i think dispensing drugs phamarcy has not been grouped by patient but i can do it here

**Comment by ojwanganto** [comment]
> > Asante
> 
> @ojwanganto i think dispensing drugs phamarcy has not been grouped by patient but i can do it here

The idea is to not have so many rows about the same patient. It greatly improves user experience if all active requests for a patient can be viewed in a single click. We just need an accordion implementation showing all the active requests. I hope this helps.

**Comment by FelixKiprotich350** [comment]
> > > Asante
> > 
> > @ojwanganto i think dispensing drugs phamarcy has not been grouped by patient but i can do it here
> 
> The idea is to not have so many rows about the same patient. It greatly improves user experience if all active requests for a patient can be viewed in a single click. We just need an accordion implementation showing all the active requests. I hope this helps.
Noted... working on it

**Review by makombe — APPROVED** [review]
Thanks @FelixKiprotich350

**Pull request merged**
